version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    # depends_on:
    #   - backend

  # backend:
  #   build: ./backend
  #   environment:
  #     - ENV=production
  #   ports:
  #     - "8000:8000"
